cameras_params:
  cam1:
    image_topic:
      type: string
      default_value: "/cam00/camera_00/color/image_raw/decompressed"
    camera_info_topic:
      type: string
      default_value: "/cam00/camera_00/color/camera_info"
    camera_frame_id:
      type: string
      default_value: "camera1_link"
  cam2:
    image_topic:
      type: string
      default_value: "/cam00/camera_01/color/image_raw/decompressed"
    camera_info_topic:
      type: string
      default_value: "/cam00/camera_01/color/camera_info"
    camera_frame_id:
      type: string
      default_value: "camera2_link"
  cam3:
    image_topic:
      type: string
      default_value: "/cam01/camera_02/color/image_raw/decompressed"
    camera_info_topic:
      type: string  
      default_value: "/cam01/camera_02/color/camera_info"
    camera_frame_id:
      type: string
      default_value: "camera3_link"
  cam4:
    image_topic:
      type: string
      default_value: "/cam02/camera_03/color/image_raw/decompressed"
    camera_info_topic:
      type: string
      default_value: "/cam02/camera_03/color/camera_info"
    camera_frame_id:
      type: string
      default_value: "camera4_link"
  # cam3:
  #   image_topic:
  #     type: string
  #     default_value: "/camera_03/color/image_raw"
  #   camera_info_topic:
  #     type: string
  #     default_value: "/camera_03/color/camera_info"
  #   camera_frame_id:
  #     type: string
  #     default_value: "camera3_link"
  # cam4:
  #   image_topic:
  #     type: string
  #     default_value: "/camera_03_04/color/image_raw"
  #   camera_info_topic:
  #     type: string
  #     default_value: "/camera_03_04/color/camera_info"  
  #   camera_frame_id:
  #     type: string
  #     default_value: "camera4_link"
  # cam3:
  #   image_topic:
  #     type: string
  #     default_value: "/camera_3/image_raw"
  #   camera_info_topic:
  #     type: string
  #     default_value: "/camera_3/camera_info"

