cam00_00:
  ros__parameters:
    camera_id: "cam_00_00"
    marker_size: 0.05
    aruco_dict: "DICT_5X5_250"
    depth_filter_max: 2.5
    quality_threshold: 0.5
    image_topic: "/cam00/camera_00/color/image_raw/decompressed"
    depth_topic: "/cam00/camera_00/depth/image_raw/decompressed"
    camera_info_topic: "/cam00/camera_00/color/camera_info"

cam00_01:
  ros__parameters:
    camera_id: "cam_00_01"
    marker_size: 0.05
    aruco_dict: "DICT_5X5_250"
    depth_filter_max: 2.5     
    quality_threshold: 0.5
    image_topic: "/cam00/camera_01/color/image_raw/decompressed"
    depth_topic: "/cam00/camera_01/depth/image_raw/decompressed"
    camera_info_topic: "/cam00/camera_01/color/camera_info" 

cam01_02:
  ros__parameters:
    camera_id: "cam_01_02"
    marker_size: 0.05
    aruco_dict: "DICT_5X5_250"
    depth_filter_max: 2.5     
    quality_threshold: 0.5
    image_topic: "/cam01/camera_02/color/image_raw/decompressed"
    depth_topic: "/cam01/camera_02/depth/image_raw/decompressed"
    camera_info_topic: "/cam01/camera_02/color/camera_info"

cam02_03:
  ros__parameters:
    camera_id: "cam_02_03"
    marker_size: 0.05
    aruco_dict: "DICT_5X5_250"
    depth_filter_max: 2.5     
    quality_threshold: 0.5
    image_topic: "/cam02/camera_03/color/image_raw/decompressed"
    depth_topic: "/cam02/camera_03/depth/image_raw/decompressed"
    camera_info_topic: "/cam02/camera_03/color/camera_info"