# === Fuente (maestro) ===
server 10.0.0.10 iburst

# === Estabilidad / Arranque ===
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/chrony.drift

# === Timestamping ===
hwtimestamp *

# === Seguridad / Acceso ===
cmdport 0

# === Logs ===
logdir /var/log/chrony
log tracking measurements statistics
