# === Fuente (maestro) ===
server 10.0.0.10 iburst xleave presend 9 minpoll 2 maxpoll 4 key 1
# minpoll 2 = ~4s; maxpoll 4 = ~16s → muy estable para LAN con maestro sin HW-TS

# === Estabilidad / Arranque ===
makestep 1.0 3
rtcsync
driftfile /var/lib/chrony/chrony.drift

# === Timestamping ===
# Esta NIC SÍ tiene HW timestamp (PTP Hardware Clock: 0)
hwtimestamp *

# === Seguridad / Acceso ===
cmdport 0                  # sin control remoto por red

# === Logs ===
logdir /var/log/chrony
log tracking measurements statistics

# === Autenticación ===
keyfile /etc/chrony.keys
commandkey 1
