aruco: 
  dictionary: DICT_5X5_100 
  marker_length_m: 0.22 
  cube_edge_m: 0.31 
markers: 
  # ID 0: Cara +Y (arriba) 
  '0': 
    T: [[ 1, 0, 0, 0.0], 
        [ 0, 0, 1, 0.155], 
        [ 0, -1, 0, 0.0], 
        [ 0, 0, 0, 1.0]] 
  # ID 1: Cara +X (derecha) 
  '1': 
    T: [[ 0, 0, 1, 0.155], 
        [ 0, 1, 0, 0.0], 
        [-1, 0, 0, 0.0], 
        [ 0, 0, 0, 1.0]] 
  # ID 2: Cara -X (izquierda) 
  '2': 
    T: [[ 0, 0, -1, -0.155], 
        [ 0, 1, 0, 0.0], 
        [ 1, 0, 0, 0.0], 
        [ 0, 0, 0, 1.0]] 
  # ID 3: Cara -Z (detrás) 
  '3': 
    T: [[ 1, 0, 0, 0.0], 
        [ 0, -1, 0, 0.0], 
        [ 0, 0, -1, -0.155], 
        [ 0, 0, 0, 1.0]] 
  # ID 4: Cara +Z (frente) (rotado 180º) 
  '4': 
    T: [[1, 0, 0, 0.0], 
        [ 0, 1, 0, 0.0], 
        [ 0, 0, 1, 0.155], 
        [ 0, 0, 0, 1.0]] 
  # ID 5: Cara -Y (abajo) 
  '5': 
    T: [[ -1, 0, 0, 0.0], 
        [ 0, 0, -1, -0.155], 
        [ 0, -1, 0, 0.0], 
        [ 0, 0, 0, 1.0]]